export enum Screens {
  ON_BOARDING,
  PHONE_RECORDING,
  PHONE_SUCCESS,
  CHOOSE_CURRENCY,
  CHOOSE_AMOUNT,
  ORDER_SUMMARY,
  PAYMENT,
  PAYMENT_SUCCESS,
  WELCOME_SCREEN,
  USER_DETAILS,
  INSERT_CODE,
  CHOOSE_REGISTER_OPTION,
  QR_REGISTER,
  LINK_REGISTER
}
